Repository shelldivers/miniRT, pull requests merged in 2024-08, with the labels that each got.

#16 15 implement geometric functions
  includes/camera.h
  includes/key_hook.h
  includes/minirt.h
  includes/ray.h
  includes/shape/hittable.h
  includes/shape/sphere.h
  includes/vec3.h
  main.c
  srcs/camera.c
  srcs/error.c
  srcs/key_hook.c
  srcs/minirt.c
  srcs/minirt_utils.c
  srcs/ray/color.c
  srcs/ray/ray.c
  srcs/shape/hittable.c
  srcs/shape/sphere.c
  srcs/vec3/vec3.c
  srcs/vec3/vec3_utils.c
  test/color_test.cpp
  test/ray_test.cpp
  test/vec3_test.cpp
Labels: enhancement

#23 19 feat parse rt file ambient lightening and light
  .github/workflows/test-validation.yml
  example.rt
  includes/camera.h
  includes/minirt.h
  includes/ray.h
  includes/reflection.h
  includes/shape/cylinder.h
  includes/shape/hittable.h
  includes/shape/plane.h
  includes/shape/sphere.h
  includes/vec3.h
  main.c
  srcs/light_lst_utils.c
  srcs/minirt.c
  srcs/minirt_parse_scene.c
  srcs/minirt_parse_shape.c
  srcs/minirt_parse_utils2.c
  srcs/minirt_parse_world.c
  srcs/minirt_utils.c
  srcs/ray/ray.c
  srcs/shape/cylinder.c
  srcs/shape/hittable.c
  srcs/shape/plane.c
  srcs/shape/sphere.c
  test/init_world_test.cpp
  test/main.cpp
  test/parse_ambient_test.cpp
  test/parse_camera_test.cpp
  test/parse_cylinder_test.cpp
  test/parse_light_test.cpp
  test/parse_plane_test.cpp
  test/parse_rtfile_test.cpp
  test/parse_sphere_test.cpp
Labels: enhancement, refactoring

#26 25 feat implement normal vector and fov of camera
  example.rt
  includes/camera.h
  includes/minirt.h
  main.c
  srcs/minirt_parse_scene.c
  srcs/minirt_utils.c
Labels: enhancement

#31 22 feat phong reflecion model #22 #27 #28
  example.rt
  includes/minirt.h
  includes/ray.h
  includes/reflection.h
  includes/vec3.h
  main.c
  srcs/minirt.c
  srcs/minirt_parse_scene.c
  srcs/minirt_utils.c
  srcs/ray/color.c
  srcs/reflection/reflection.c
  srcs/reflection/reflection_utils.c
  srcs/shape/hittable.c
  srcs/vec3/vec3_utils.c
  test/color_test.cpp
Labels: enhancement

#34 32 fix diffused reflection by using light ratio
  example.rt
  srcs/minirt.c
  srcs/reflection/reflection.c
Labels: bug

#35 33 fix surface normal vector
  srcs/minirt.c
  srcs/shape/cone.c
  srcs/shape/cylinder.c
  srcs/shape/plane.c
  srcs/shape/sphere.c
Labels: bug

#37 #36 fix add reflection const
  example.rt
  includes/reflection.h
  srcs/minirt.c
  srcs/reflection/reflection.c
  srcs/shape/sphere.c
Labels: enhancement

#42 41 fix camera z axis bug
  includes/error.h
  srcs/parse/minirt_parse_utils2.c
  test/normalize_vec3_test.cpp
Labels: bug

#46 43 feat anti aliasing and multi threading
  includes/error.h
  includes/minirt.h
  includes/mlx_hook.h
  includes/parse.h
  includes/ray.h
  includes/shape/hittable.h
  main.c
  srcs/minirt.c
  srcs/minirt_async.c
  srcs/minirt_color.c
  srcs/mlx_hook/key_hook.c
  srcs/mlx_hook/loop_hook.c
  srcs/parse/minirt_parse.c
  srcs/parse/minirt_parse_scene.c
  srcs/parse/minirt_parse_shape.c
  srcs/parse/minirt_parse_texture.c
  srcs/parse/minirt_parse_texture2.c
  srcs/parse/minirt_parse_vec3.c
  srcs/parse/minirt_parse_world.c
  srcs/ray/ray.c
  srcs/shape/cone.c
  srcs/shape/cylinder.c
  srcs/shape/plane.c
  srcs/shape/sphere.c
  srcs/vec3/vec3.c
  srcs/vec3/vec3_utils.c
  test/color_test.cpp
  test/extension_valid_test.cpp
  test/init_world_test.cpp
  test/normalize_vec3_test.cpp
  test/parse_ambient_test.cpp
  test/parse_camera_test.cpp
  test/parse_cone_test.cpp
  test/parse_cylinder_test.cpp
  test/parse_light_test.cpp
  test/parse_plane_test.cpp
  test/parse_rtfile_test.cpp
  test/parse_sphere_test.cpp
  test/parse_vec3_test.cpp
Labels: enhancement

#47 44 test add test for parse texture
  includes/error.h
  srcs/parse/minirt_parse_texture.c
  srcs/shape/texture.c
  test/color_test.cpp
  test/main.cpp
  test/parse_cone_test.cpp
  test/parse_texture_test.cpp
Labels: test

#52 51 bug 확장자 segfault 발생
  bonus/includes/error_bonus.h
  bonus/srcs/parse/minirt_parse_utils3_bonus.c
  mandatory/includes/error.h
  mandatory/srcs/parse/minirt_parse_utils3.c
  mlx/Makefile
  mlx/interface.swift
Labels: bug
